import { writeFile } from "node:fs/promises";

import { createRequester } from "../request.ts";
import { listColumns, listTables, type RawColumn } from "./introspect.ts";
import type { ResolvedConfig } from "./config.ts";

export interface GenerateOptions {
  out: string;
  typeName: string;
}

export async function runGenerate(config: ResolvedConfig, options: GenerateOptions): Promise<void> {
  const requester = createRequester(config);
  const tables = await listTables(requester);

  const tableEntries: string[] = [];
  for (const table of tables) {
    const columns = await listColumns(requester, table.id);
    tableEntries.push(renderTable(table.id, columns));
  }

  const source = `// Generated by grist-kit. Do not edit by hand.\n\nexport type ${options.typeName} = {\n${tableEntries.join("\n")}\n};\n`;
  await writeFile(options.out, source, "utf8");
}

function renderTable(tableId: string, columns: RawColumn[]): string {
  const lines = [`  ${quoteKey(tableId)}: {`];
  for (const column of columns) {
    if (isSystemColumn(column.id)) continue;
    lines.push(`    ${quoteKey(column.id)}: ${renderColumn(column)};`);
  }
  lines.push("  };");
  return lines.join("\n");
}

function renderColumn(column: RawColumn): string {
  const type = column.fields.type ?? "Any";
  const parts: string[] = [];
  const base = mapColumnType(type);
  parts.push(`type: ${JSON.stringify(base.type)}`);
  if (base.table !== undefined) parts.push(`table: ${JSON.stringify(base.table)}`);

  if (base.type === "Choice" || base.type === "ChoiceList") {
    const choices = extractChoices(column.fields.widgetOptions);
    if (choices && choices.length > 0) {
      const literal = choices.map((c) => JSON.stringify(c)).join(", ");
      parts.push(`choices: [${literal}]`);
    }
  }

  if (column.fields.isFormula) parts.push("isFormula: true");
  return `{ ${parts.join("; ")} }`;
}

interface ColumnTypeInfo {
  type: string;
  table?: string;
}

function mapColumnType(raw: string): ColumnTypeInfo {
  if (raw.startsWith("Ref:")) return { type: "Ref", table: raw.slice(4) };
  if (raw.startsWith("RefList:")) return { type: "RefList", table: raw.slice(8) };

  switch (raw) {
    case "Text":
    case "Numeric":
    case "Int":
    case "Bool":
    case "Date":
    case "DateTime":
    case "Choice":
    case "ChoiceList":
    case "Attachments":
      return { type: raw };
    default:
      return { type: "Any" };
  }
}

function extractChoices(widgetOptions: unknown): string[] | null {
  if (typeof widgetOptions !== "string" || !widgetOptions) return null;
  try {
    const parsed = JSON.parse(widgetOptions) as { choices?: unknown };
    return Array.isArray(parsed.choices)
      ? parsed.choices.filter((c): c is string => typeof c === "string")
      : null;
  } catch {
    return null;
  }
}

function isSystemColumn(id: string): boolean {
  return id.startsWith("gristHelper_") || id === "manualSort";
}

function quoteKey(id: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(id) ? id : JSON.stringify(id);
}
