// Generated by grist-kit. Do not edit by hand.

export type GristSchema = {
  All_Products: {
    Color: { type: "Ref"; table: "Color"; isFormula: true };
    Brand: { type: "Ref"; table: "Add_Products"; isFormula: true };
    Size: { type: "Choice"; choices: ["28", "30", "32", "34", "36", "38", "40"] };
    Received: { type: "Numeric"; isFormula: true };
    In_Stock: { type: "Numeric"; isFormula: true };
    SKU: { type: "Text"; isFormula: true };
    Sold: { type: "Numeric"; isFormula: true };
    Cost_per_Unit: { type: "Numeric"; isFormula: true };
    Stock_Alert: {
      type: "Choice";
      choices: ["Low Stock", "OUT OF STOCK", "Place Initial Order", "In Stock"];
      isFormula: true;
    };
    QTY_on_Order: { type: "Numeric"; isFormula: true };
    Product_Variant_Description: { type: "Ref"; table: "Product_Variant" };
    Product: { type: "Text"; isFormula: true };
  };
  Add_Products: {
    Name_Brand: {
      type: "Choice";
      choices: [
        "Viva Who",
        "Vegan Only",
        "Sew it Seams",
        "Indiana Jeans",
        "Tulles of the Trade",
        "Tiecoon",
      ];
    };
    Product: { type: "Text" };
    Brand_Code: { type: "Text" };
  };
  Color: {
    Color: {
      type: "Choice";
      choices: [
        "Black",
        "Khaki",
        "Brown",
        "Grey",
        "Multi",
        "Army Green",
        "Blue",
        "Navy",
        "Light Blue",
      ];
    };
    Code: { type: "Text" };
  };
  Incoming_Orders: {
    Order_Number: { type: "Date"; isFormula: true };
    Order_Date: { type: "Date" };
    Status: { type: "Choice"; choices: ["Order Placed", "Production", "Shipped", "Received"] };
    Total: { type: "Numeric"; isFormula: true };
    Tanggal_Diterima: { type: "Date" };
  };
  Product_Variant: {
    Name_Brand: { type: "Ref"; table: "Add_Products" };
    Color: { type: "Ref"; table: "Color" };
    Photos: { type: "Attachments" };
    Product: { type: "Any"; isFormula: true };
    Color_Code: { type: "Any"; isFormula: true };
    Description: { type: "Text"; isFormula: true };
    Cost_per_Unit: { type: "Numeric" };
  };
  Incoming_Order_Line_Items: {
    Order_Number: { type: "Ref"; table: "Incoming_Orders" };
    SKU: { type: "Ref"; table: "All_Products" };
    Qty: { type: "Numeric" };
    Cost_per_Unit: { type: "Numeric"; isFormula: true };
    Total: { type: "Numeric"; isFormula: true };
    Received_Qty: { type: "Numeric"; isFormula: true };
  };
  Outgoing_Orders: {
    Name: { type: "Text" };
    Phone: { type: "Text" };
    Email: { type: "Text" };
    Financial_Status: { type: "Choice"; choices: ["Paid in Full", "Partial Payment", "Unpaid"] };
    Paid_At: { type: "Date" };
    Fulfillment_Status: { type: "Choice"; choices: ["Fulfilled", "In Process", "Order Received"] };
    Currency: { type: "Text" };
    Subtotal: { type: "Numeric" };
    Taxes: { type: "Numeric" };
    Shipping: { type: "Numeric" };
    Discount_Code: { type: "Text" };
    Total: { type: "Numeric"; isFormula: true };
    Shipping_Method: { type: "Choice"; choices: ["USPS", "FedEx", "UPS"] };
    Discount_Amount: { type: "Numeric" };
    Created_At: { type: "Any" };
    Lineitem_Quantity: { type: "Numeric" };
    Line_item_Name: { type: "Any"; isFormula: true };
    Line_Item_Price: { type: "Numeric"; isFormula: true };
    Line_Item_SKU: { type: "Ref"; table: "All_Products" };
    Billing_Name: { type: "Text" };
    Billing_Address_1: { type: "Text" };
    Billing_Street: { type: "Text" };
    Billing_City: { type: "Text" };
    Billing_Address_2: { type: "Text" };
    Billing_Country: { type: "Text" };
    Billing_Zip: { type: "Numeric" };
    Billing_State: { type: "Text" };
    Billing_Phone: { type: "Text" };
    Shipping_Street: { type: "Text" };
    Shipping_Name: { type: "Text" };
    Shipping_Address_1: { type: "Text" };
    Shipping_Address_2: { type: "Text" };
    Shipping_City: { type: "Text" };
    Shipping_State: { type: "Text" };
    Shipping_Zip: { type: "Text" };
    Shipping_Country: { type: "Text" };
    Shipping_Phone: { type: "Text" };
    Notes: { type: "Text" };
    Cancelled_At: { type: "Text" };
    Payment_Method: { type: "Text" };
    Refunded_Amount: { type: "Text" };
    Outstanding_Balance: { type: "Numeric"; isFormula: true };
    Order_ID: { type: "Numeric" };
    Amount_Paid: { type: "Numeric" };
  };
  GristDocTour: {
    Title: { type: "Text" };
    Body: { type: "Text" };
    Placement: { type: "Text" };
    Location: { type: "Text"; isFormula: true };
    LocationCell: { type: "Text" };
  };
};
